### ISSUE TITLE
下载模型需要申请授权

### ISSUE THREAD

**Issue by jiushaba** [Symbolzzz/audio2shapes#1]
![image](https://github.com/Symbolzzz/audio2shapes/assets/26453056/211f71b7-671e-4610-bbc2-a2a693db983f)

**Comment by Symbolzzz** [comment]
> ![image](https://private-user-images.githubusercontent.com/26453056/337059679-211f71b7-671e-4610-bbc2-a2a693db983f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzUxOTIsIm5iZiI6MTcxNzczNDg5MiwicGF0aCI6Ii8yNjQ1MzA1Ni8zMzcwNTk2NzktMjExZjcxYjctNjcxZS00NjEwLWJiYzItYTJhNjkzZGI5ODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA0MzQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZjhkZWJlMjFiYTcxMDc1Zjk5NzEzNDFmMjM5YjhiNWQyOTZjZjE4MWFmNTdhNzdiZmEyNDVhYWRkNzNhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eiFaz999Z0IXej04d9xlBvKJ1k_BTDbUNuouNnV3DV0)

你好，我已经修改了权限，你可以再试一下

**Comment by jiushaba** [comment]
谢谢
